name: AQA Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8 .

  unit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - name: Run unit tests
        run: pytest -m unit

  api:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - name: Run api tests with Allure
        run: pytest -m api --alluredir=allure-results

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  report:
    runs-on: ubuntu-latest
    needs: api
    steps:
      - uses: actions/checkout@v3

      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
