name: AQA Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install flake8

      - name: Lint
        run: flake8 . || true

  unit:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest -m unit

  api:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run API tests
        run: pytest --alluredir=allure-results

      - name: Ensure results exist
        run: |
          mkdir -p allure-results
          echo "ok" > allure-results/dummy.txt

      - name: Upload allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  report:
    runs-on: ubuntu-latest
    needs: api

    steps:
      - uses: actions/checkout@v3

      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          allure_report: allure-report
